### ISSUE TITLE
Can we replace *testing T with an interface?

### ISSUE THREAD

**Issue by anthonyfong100** [steinfletcher/apitest#105]
**Is your feature request related to a problem? Please describe.**
When using apitest to do testing of api, the Expect method takes in a *testing T pointer which is a concrete type. This makes interacting with other third party testing library like Ginkgo difficult. 

**Describe the solution you'd like**
Replace the reliance on *testing.T with an interface. 

From the developer of ginkg:
***
It looks like testify uses (*testing.T) directly instead of an interface (which gomock does). Ginkgo can provide such frameworks with a Fail function that one can wrap in such a way to satisfy most interfaces (this is how we support go mock), but *testing.T refers to a concrete type and passing in the testing.T for the test that Ginkgo runs in would cause the entire suite to fail should one of your mock assertions fail...
***

**Describe alternatives you've considered**
As per the section above another way would to just pass in the testing.T but would cause the entire suite to fail if one of the assertions fail. 

**Additional context**
Other libraries such as testify have changed this to support ginkgo [integration](https://github.com/stretchr/testify/pull/32)

I would be happy to create a PR if this is possible

**Comment by steinfletcher** [comment]
Hi @anthonyfong100. This sounds very useful. Would be happy to take a PR for this.

Cheers

**Comment by anthonyfong100** [comment]
Hey @steinfletcher i was thinking more along the lines of passing in an interface to replace the `*testing.T` and continue using testify to do the assertions. As of now, testify already supports accepting an interface `testingT` as its argument in place of the concrete class `*testing.T`. This solution is likely to be better as it allows us to leverage on numerous other assertion methods defined in testify. Do let me know your thoughts on this

**Comment by steinfletcher** [comment]
Hello @anthonyfong100. Sorry I wasn't clear. I also agree that there should be an interface `TestingT`. I was just adding some info on the existing design around assertions, which is completely compatible with the approach you suggest. 

I'll be removing testify in a future commit, but that doesn't really affect your changes :)

**Comment by anthonyfong100** [comment]
okay @steinfletcher that sounds wonderful i will go ahead with writing the PR then

**Comment by steinfletcher** [comment]
Looks great @anthonyfong100. Many thanks!
