### ISSUE TITLE
option to output sequence diagram with custom name instead of hash

### ISSUE THREAD

**Issue by sswastioyono18** [steinfletcher/apitest#116]
**Is your feature request related to a problem? Please describe.**
not really

**Describe the solution you'd like**
currently when apitest produce sequence diagram , it creates a file name by using hash. 
```
meta["name"] = a.name
meta["hash"] = createHash(meta)
```
I want to produce the output with custom name such as "unit-test-feature-a" and probably we can just use the test name when we define the test name [here](https://github.com/steinfletcher/apitest/blob/master/apitest.go#L75)

**Describe alternatives you've considered**
provide option so we can use custom name. Maybe additional param or boolean flag to use name

**Additional context**

**Comment by steinfletcher** [comment]
Hi @sswastioyono18. This seems like a sensible ask. Happy to take a PR - I am a little busy right now so might not get to this for a while.

However, I think you might be able to do this already without changes (although it would be nice to support it out of the box).

In `diagram.go`, we already override the system under test and consumer names like so


```go
func (r *webSequenceDiagramDSL) addRow(operation, source string, target string, description string) {
	if name, ok := r.meta["consumerName"]; ok {
		if n, ok := name.(string); ok {
			source = strings.ReplaceAll(source, ConsumerDefaultName, n)
			target = strings.ReplaceAll(target, ConsumerDefaultName, n)
		}
	}
	if name, ok := r.meta["systemUnderTestName"]; ok {
		if n, ok := name.(string); ok {
			source = strings.ReplaceAll(source, SystemUnderTestDefaultName, n)
			target = strings.ReplaceAll(target, SystemUnderTestDefaultName, n)
		}
	}
	r.count++
	r.data.WriteString(fmt.Sprintf("%s%s%s: (%d) %s\n",
		quoted(source),
		operation,
		quoted(target),
		r.count,
		description),
	)
}
```

The values are picked up from the metadata object provided in tests. See the example `sequence-diagrams-with-sqlite-database`.

So, in theory you could keep your own version of diagram.go which gets provided to apitest.

**Comment by sswastioyono18** [comment]
I see. My case is quite specific though so might as well fork and use my own version.

One more question, I'm planning to use for integration test and I don't want to mock external call. 
is it possible for the sequence diagram to draw _real_ external call instead mocked one?

**Comment by steinfletcher** [comment]
@sswastioyono18 we currently only record reporting events on 1. request, 2. mocks and 3. response - not on the default http transport.

We do provide a way to write your own recorder to register events, there are some examples for SQL queries. You could follow the same approach, but you would need to inject a custom http transport that does the recording - then your code uses that for http requests.
