### ISSUE TITLE
multipart/form-data sending file

### ISSUE THREAD

**Issue by maranqz** [steinfletcher/apitest#118]
**Is your feature request related to a problem? Please describe.**
I want to send multipart/form-data with file.

**Comment by steinfletcher** [comment]
Hi @maranqz. Thank you for the request.

I'd be happy to support this. I don't have time right now to add this, but I'm happy to take a contribution. I'll leave the issue open and might get to it in future. 

It should be possible currently to add a file by manually creating a http.Request.
