### ISSUE TITLE
Failed test in VScode keep trying to open assert.go file

### ISSUE THREAD

**Issue by ItamarShDev** [steinfletcher/apitest#128]
### **Describe the bug**
when running directly from vscode, every failed test opens a non-existed `assert.go` file
![Screenshot 2022-12-01 at 12 30 12](https://user-images.githubusercontent.com/953371/205030787-e4834c1e-9ea1-4f6f-aa40-8ed247b69610.png)

**Steps to reproduce**
- create a failing test
- click VSCode run button

**Expected behavior**
Fail message should show in vscode (as other testing libraries)
**Additional context**
I guess it related the fact that this is in the output? 
![Screenshot 2022-12-01 at 12 33 52](https://user-images.githubusercontent.com/953371/205030761-74b3bd9c-d380-45e5-8ea1-7261ed835efc.png)

**Comment by steinfletcher** [comment]
Hey, I don't think there is an issue here with apitest here, looks like your test is failing because of a 405 - method not allowed. Going to close this one.

**Comment by ItamarShDev** [comment]
Sorry I wasn't clear. The test should fail.
The issue is the when test fails, VSCode opens a file called `assert.go`
for some reason.
There is no such file.

So the fail error is not shown in the editor.

I think it relates to how the library report the error.
