### ISSUE TITLE
Difficult to see why mocks failed to match

### ISSUE THREAD

**Issue by steinfletcher** [steinfletcher/apitest#16]
It is pretty common to spend time debugging mocks that failed to match. We should provide some debug output to assist the user. This should be disabled by default. The debug output should record each request and the results against the mock under test. It should be possible for the user to then identify which request attribute failed to match, e.g. the http method or request body.

How we best present the information requires some thought and discussion. Ideally we'd have a nice table of results but we don't want to add any external dependencies for this, so let's keep it simple for now.

**Comment by fergusstrange** [comment]
@steinfletcher is this resolved with [this](https://github.com/steinfletcher/apitest/commit/5475ae4400bbcc4e62b32e2cd4d4c73f32104287) commit?

**Comment by steinfletcher** [comment]
Hey @fergusstrange. That commit does help investigate failing matches but the intention here is to log why the request failed to match the requests, e.g. to log which matcher failed - method, body, host, header etc. Not sure what the output should look like, but maybe we can just enable this in debug mode as enabled [here](https://github.com/steinfletcher/apitest/commit/5475ae4400bbcc4e62b32e2cd4d4c73f32104287). It might be good to just log in the same request dump section an extra line, currently, if you edit `TestMocks_ApiTest_WithMocks` to force a failure, e.g. change the URL

```go
NewMock().Get("/preferencesssssssss").
```

we output

```
----------> request to mock
GET /preferences HTTP/1.1
Host: localhost:8080
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip

<---------- response from mock

panic: Get http://localhost:8080/preferences: failed to match any of the defined mocks [recovered]
	panic: Get http://localhost:8080/preferences: failed to match any of the defined mocks
```

But it would be nice to log which matcher failed. This would need to be done per registered mock. Might be OK to refer to the mocks by number, e.g. 1, 2, 3 rather than logging the spec, e.g.

```
mock 1: failed to match body
```

**Comment by fergusstrange** [comment]
@steinfletcher check out build https://travis-ci.org/steinfletcher/apitest/jobs/487268747#L808

This is a bit of a hack around to see how it might look and the code will need tidying up but what do you think about implementation and presentation of the mismatched mocks?

We could go a step further and highlight which fields are mismatched but this may be a good start...

**Comment by steinfletcher** [comment]
Thanks @fergusstrange this is good. Can we also add which matcher failed? I think it's easy to get the data since we make a call to each matcher and then fail fast.

I think instead of the matchers returning bool, they can return errors.New("failed to match body"). Or something similar, then check for nil on the error instead of the bool check.

**Comment by fergusstrange** [comment]
@steinfletcher something like the changes to get to here: https://travis-ci.org/steinfletcher/apitest/jobs/488031119#L696

This will currently only expose if the client code panics but could be stored and replayed as part of the report if you wanted at the end of a run? Use case might be matching the wrong mock by accident and getting a false positive?

If this looks okay then I will jazz up the code a little and add the failure reporting as a second pass.

**Comment by steinfletcher** [comment]
In `RoundTrip`, it looks like `mockResponse` never gets set. So it never gets passed to the observer. That might explain the failing tests.

**Comment by fergusstrange** [comment]
@steinfletcher resolved [here](https://github.com/steinfletcher/apitest/commit/4066c34546de16921b68c3d90b5ea88eb6b7c892) nice spot. Though not a fan of the assign variable then use in defer block. Seems pretty grim. Gimme a little time to tidy up and will open PR.
