### ISSUE TITLE
Rename this repo to `apitest`

### ISSUE THREAD

**Issue by gaw508** [steinfletcher/apitest#21]
A **really annoying** thing, I know, but maybe something to consider early on before this is used by many people:

The package name is different to the repo name, which means when you run `go imports` in a project which has this lib as a dependency, you get really ugly imports at the top, where there is an alias.

You can't, unfortunately, just change the package name to be `api-test` either, as this will make a different alias, with an underscore: `api_test "github.com/steinfletcher/api-test"`. 

Really annoying from the go imports tool, but it's really commonly used, and this is the kind of thing that will annoy a load of complete pricks like me ha.

### Examples

```golang
import (
	// Current ugly alias
	apitest "github.com/steinfletcher/api-test"

	// Ugly alias if package name is changed to match repo name "api_test"
	api_test "github.com/steinfletcher/api-test"

	// Beautiful package name with repo name change, and no alias
	"github.com/steinfletcher/apitest"
)
```

**Also see: ** See https://blog.golang.org/package-names

**Comment by steinfletcher** [comment]
Yes. I was actually contemplating a completely different name. What do you think?

**Comment by steinfletcher** [comment]
Done

**Comment by gaw508** [comment]
Ah, nice one mate.

The name change idea sounds good, did you have some ideas in mind already?
