### ISSUE TITLE
Sainsburys SmartShop bug report

### ISSUE THREAD

**Issue by nabilfreeman** [steinfletcher/apitest#45]
Hey there, sorry for filing an issue here but I can't find a way to report a bug to Sainsburys and I saw you work there.

I signed up for a SmartShop account for their new store in Holborn.

The app accepted a signup with nabil+smartshop@xyz.com.

But the login API endpoint doesn't accept email addresses with a + sign.

Forgot password works.

Could you forward to the SmartShop team? I would create another account, but my Nectar card is now linked to the broken account.

Sorry again for the hijack. It would be great if Sainsburys had a bigger OSS presence.

**Comment by nabilfreeman** [comment]
It would be great if they could fix this too
<img width="776" alt="Screenshot 2019-05-20 at 14 56 09" src="https://user-images.githubusercontent.com/2470659/58026894-6faf5c00-7b0f-11e9-90d1-c9cb60a7d0f2.png">

**Comment by steinfletcher** [comment]
Forwarded
