### ISSUE TITLE
Echo - Assert body contains ID (string)

### ISSUE THREAD

**Issue by TudorHulban** [steinfletcher/apitest#78]
Hi,
I started writing my tests with apitest.
Please advise if I could assert the response body that it contains the ID of the just inserted row.
```
return c.String(http.StatusCreated, strconv.FormatInt(user.ID, 10))
```
and test
```
		apitest.New().
			Handler(e).
			Method(http.MethodPost).
			URL(commons.EndpointNewUser).
			FormData("code", "AB").
			FormData("pass", "abcd").
			Expect(t).
			Status(http.StatusCreated).
			End()
	}
```
I did not find this case in examples. 

Or the only option would be to send it as JSON?
With JSON what should I use? jsonpath.Present("ID") for a {"ID":1} response? ( I cannot place a number to equal as the ID is incremented at each insert.)

Thank you!

**Comment by gaw508** [comment]
Hey,

I would suggest using JSON for your responses. If you do, you can test that using the apitest jsonpath library (https://github.com/steinfletcher/apitest-jsonpath). You can see example of this library on the apitest.dev website https://apitest.dev/docs/assertions/

For your specific scenario I would do:

```go
import github.com/steinfletcher/apitest-jsonpath

apitest.New().
	Handler(e).
	Method(http.MethodPost).
	URL(commons.EndpointNewUser).
	FormData("code", "AB").
	FormData("pass", "abcd").
	Expect(t).
	Status(http.StatusCreated).
	Assert(jsonpath.Matches(`$.ID`, `^\d+$`)).
	End()
```

This will assert that the ID field in your JSON response matches the regex `^\d+$` (contains 1 or more digits

For these type of questions you might be better off joining our new community slack channel, **#apitest**, on the gophers slack (a slack org with 50,000+ go developers), gophers.slack.com. If you are not already a member the go lang bridge has a sign up form to join: **https://invite.slack.golangbridge.org/**

Thanks,
George
