### ISSUE TITLE
Site example

### ISSUE THREAD

**Issue by TudorHulban** [steinfletcher/apitest#88]
**Describe the bug**
In https://github.com/steinfletcher/apitest-jsonpath
Example:
```
apitest.New().
	Handler(handler).
	Get("/articles?category=golang").
	Expect(t).
	Assert(jsonpath.Len(`$.items`, 3).
	End()
```
Misses closing parentheses in assert.

**Comment by webbgeorge** [comment]
thanks @TudorHulban - I'll raise an issue on that repo
