### ISSUE TITLE
Site example

### ISSUE THREAD

**Issue by TudorHulban** [steinfletcher/apitest#89]
**Describe the bug**
Example ( https://github.com/steinfletcher/apitest-jsonpath ):
```
apitest.New().
	Handler(handler).
	Get("/hello").
	Expect(t).
	Assert(Present(`$.a`)).
	Assert(NotPresent(`$.password`)).
	End()
```
should be:
```
apitest.New().
	Handler(handler).
	Get("/hello").
	Expect(t).
	Assert(jsonpath.Present(`$.a`)).
	Assert(jsonpath.NotPresent(`$.password`)).
	End()
```
Better UX as people loking on site are just learning.

**Comment by TudorHulban** [comment]
Maybe examples could be also ordered by the response. Currently after /hello there is a jump to /articles and get back to /hello.<br/>
For article maybe the JSON response could be present.

**Comment by steinfletcher** [comment]
Thanks for this @TudorHulban. I'd be happy to take a PR for the missing `jsonpath` package.

**Comment by TudorHulban** [comment]
Will try to do it over this weekend.

**Comment by TudorHulban** [comment]
Hope the content could be useful...

**Comment by steinfletcher** [comment]
Resolved in apitest-jsonpath repo
